#!/usr/bin/env python
import numpy as np
import sys
from globalfile import readglobal
import datetime
import numba
import os

@numba.jit(nogil=True,nopython=True,cache=True)
def fna(t11,t22,t33,t12,t13,t23,d12,d13,d23,d11,d22,d33,pr):
  Nx,Ny,Nz = pr.shape
  for k in range(Nz):
    for j in range(Ny):
      for i in range(Nx):
        pr[i,j,k] = -(((2*t11[i,j,k] - t22[i,j,k] - t33[i,j,k])/3)*d11[i,j,k] + ((2*t22[i,j,k] - t11[i,j,k] - t33[i,j,k])/3)*d22[i,j,k] + ((2*t33[i,j,k] - t11[i,j,k] - t22[i,j,k])/3)*d33[i,j,k] + 2*(t12[i,j,k]*d12[i,j,k] + t13[i,j,k]*d13[i,j,k] + t23[i,j,k]*d23[i,j,k]))
  return

@numba.jit(nogil=True,nopython=True,cache=True)
def fa(t11,t22,t33,t12,t13,t23,d12,d13,d23,d11,d22,d33,pr):
  Nx,Ny,Nz = pr.shape
  for k in range(Nz):
    for j in range(Ny):
      for i in range(Nx):
        pr[i,j,k] = -(t11[i,j,k]*d11[i,j,k] + t22[i,j,k]*d22[i,j,k] + t33[i,j,k]*d33[i,j,k] + 2*(t12[i,j,k]*d12[i,j,k] + t13[i,j,k]*d13[i,j,k] + t23[i,j,k]*d23[i,j,k]))
  return


Fil = sys.argv[1]
N = sys.argv[2]
if os.path.exists('./global'): path='./'
elif os.path.exists('../global'): path='../'
elif os.path.exists('../../global'): path='../../'
elif os.path.exists('../../../global'): path='../../../'
elif os.path.exists('../../../../global'): path='../../../../'
elif os.path.exists('../../../../../global'): path='../../../../../'
else: path = input('Please specify global file directory path: ')

nx,ny,nz,xDomainSize,yDomainSize,zDomainSize = readglobal(path=path)

try:
  d11 = np.memmap(Fil+'D11_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  d12 = np.memmap(Fil+'D12_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  d13 = np.memmap(Fil+'D13_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  d22 = np.memmap(Fil+'D22_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  d23 = np.memmap(Fil+'D23_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  d33 = np.memmap(Fil+'D33_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')

except:
  try:
    d11 = np.memmap('../'+Fil+'D11_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d12 = np.memmap('../'+Fil+'D12_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d13 = np.memmap('../'+Fil+'D13_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d22 = np.memmap('../'+Fil+'D22_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d23 = np.memmap('../'+Fil+'D23_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d33 = np.memmap('../'+Fil+'D33_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  except:
    d11 = np.memmap('../../'+Fil+'D11_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d12 = np.memmap('../../'+Fil+'D12_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d13 = np.memmap('../../'+Fil+'D13_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d22 = np.memmap('../../'+Fil+'D22_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d23 = np.memmap('../../'+Fil+'D23_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
    d33 = np.memmap('../../'+Fil+'D33_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  
try:
  t11 = np.memmap(Fil+'T11_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t12 = np.memmap(Fil+'T12_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t13 = np.memmap(Fil+'T13_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t22 = np.memmap(Fil+'T22_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t23 = np.memmap(Fil+'T23_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t33 = np.memmap(Fil+'T33_N'+N,shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  anisotropic = False
except:
  t11 = np.memmap('Tm11',shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t12 = np.memmap('Tm12',shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t13 = np.memmap('Tm13',shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t22 = np.memmap('Tm22',shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t23 = np.memmap('Tm23',shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  t33 = np.memmap('Tm33',shape=(nx,ny,nz),order='F',dtype='float64',mode='r')
  anisotropic = True



pr = np.memmap('Pr',shape=(nx,ny,nz),order='F',dtype='float64',mode='w+')


a = datetime.datetime.now().replace(microsecond=0)

print('Performing Calculations')

if anisotropic:
  fa(t11,t22,t33,t12,t13,t23,d12,d13,d23,d11,d22,d33,pr)
else:
  fna(t11,t22,t33,t12,t13,t23,d12,d13,d23,d11,d22,d33,pr)

print('Done\n')
b = datetime.datetime.now().replace(microsecond=0)
print('Total time: {}\n'.format(b-a))
