#!/usr/bin/env python

import sys
import os
import numpy as np
import matplotlib.pyplot as plt

filename = sys.argv[1:]

plt.rcParams['legend.loc'] = 'best'
#plt.rc('text', usetex=True)
plt.rc('font', family='serif')
fig = plt.figure()#facecolor='black'

ax = [None]*len(filename)
index = [None]*len(filename)
plot = [None]*len(filename)
for i, files in enumerate(filename):
  if files.split(".")[-1] == "npy":
    xy = np.load(files)
  elif files.split(".")[-1] == "txt":
    xy = np.loadtxt(files)
  ax[i] = fig.add_subplot(111)
  plot[i]=ax[i].plot(xy[:,0],xy[:,1],'-',label=files.split(".")[0])
  ax[i].legend()
  ax[i].grid(True)
plt.show()
